# Generated by Django 4.2.5 on 2023-10-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestador', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='explicacao',
            field=models.TextField(blank=True, null=True, verbose_name='Explicação'),
        ),
    ]
