# Generated by Django 4.2.5 on 2023-10-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_alter_negativa_texto'),
        ('prestador', '0006_solicitacao_demanda_solicitacao_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='triagem.cliente'),
        ),
    ]
