# Generated by Django 4.2.5 on 2023-10-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_alter_negativa_texto'),
        ('prestador', '0003_alter_atualizacao_explicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='demanda',
            field=models.ManyToManyField(blank=True, to='triagem.demanda'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='processo',
            field=models.ManyToManyField(blank=True, to='prestador.processo'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False, verbose_name='concluída')),
                ('enviada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triagem.cliente')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.AddField(
            model_name='anexo',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prestador.solicitacao'),
        ),
    ]
