# Generated by Django 4.2.5 on 2023-10-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_alter_negativa_texto'),
        ('prestador', '0005_anexo_validado_alter_anexo_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='demanda',
            field=models.ManyToManyField(blank=True, to='triagem.demanda'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='processo',
            field=models.ManyToManyField(blank=True, to='prestador.processo'),
        ),
    ]
