# Generated by Django 4.2.5 on 2023-10-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='acolhida',
            field=models.BooleanField(default=False),
        ),
    ]
