# Generated by Django 4.2.5 on 2023-10-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_demanda_acolhida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dados',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.TextField(blank=True, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.IntegerField(blank=True, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
